version: '3'
services:
  converterapp:
    container_name: converterapp
    restart: always
    build: ../../../
    volumes:
      - ../../../data/converter/logs:/home/bot/app/logs
      - ../../../data/shr:/tmp/shr
    ports:
      - 5005:5005
    env_file:
      - .env
    depends_on:
      - db
      - converterredis
      - url2api
      - convertermtproto
      - converterbotapi
  db:
    container_name: db
    image: postgres:alpine
    restart: always
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - 5431:5432
    env_file:
      - .db.env
  converterredis:
    container_name: converterredis
    image: redis:alpine
    restart: always
    command:
      - 'redis-server'
      - '--save 900 1'
      - '--save 300 10'
      - '--save 60 10000'
    volumes:
      - ../../../data/converter/redis:/data
  url2api:
    container_name: url2api
    restart: always
    build: ../../../../url-to-pdf-api/
  convertermtproto:
    container_name: convertermtproto
    restart: always
    build: ../../../../fileutils-rest/
    env_file:
      - .env
    volumes:
      - ../../../data/converter/gram:/home/bot/app/gram
      - ../../../data/shr:/tmp/shr
    depends_on:
      - converterbotapi
  converterbot:
    container_name: converterbot
    restart: always
    build: ../../../../fileutils-bot/
    env_file:
      - .env
    volumes:
      - ../../../data/converter/gram:/home/bot/app/gram
    depends_on:
      - converterapp
  converterbotapi:
    container_name: converterbotapi
    restart: always
    build: ../../../../fileutils-bot-api/
    env_file:
      - .env
    volumes:
      - ../../../data/converter/logs:/app/logs
      - ../../../data/shr:/tmp/shr
volumes:
  pgdata:
    external: true
