version: '3'
services:
  app:
    container_name: app
    restart: always
    build: ../../../
    volumes:
      - ${PWD}/data/logs:/home/bot/app/logs
        - ../../../data/shr:/tmp/shr
    ports:
      - 5005:5005
    env_file:
      - .env
    depends_on:
      - db
      - redis
      - url2api
      - rest
  url2api:
    container_name: url2api
    restart: always
    build: ../../../../url-to-pdf-api/
  rest:
    container_name: rest
    restart: always
    build: ../../../../fileutils-rest/
    env_file:
      - ../../../../fileutils-rest/.env
    volumes:
      - ../../../data/gram:/home/bot/app/gram
      - ../../../data/shr:/tmp/shr
  bot:
    container_name: bot
    restart: always
    build: ../../../../fileutils-bot/
    env_file:
      - ../../../../fileutils-bot/.env
    volumes:
      - ../../../data/gram:/home/bot/app/gram
    depends_on:
      - app

