version: '2.4'
services:
  videoconverter:
    container_name: videoconverter
    restart: always
    build:
      context: ../../../
      dockerfile: video/Dockerfile
    volumes:
      - ../../../data/converter/logs:/home/bot/app/logs
      - ../../../data/converter/oom:/home/bot/app/oom
      - ../../../data/media/downloads:/tmp/media/downloads
      - ../../../data/media/uploads:/tmp/media/uploads
      - ../../../data/media/temp:/tmp/media/temp
      - ../../../../fonts:/usr/share/fonts/converter
      - ../../../data/botapi/workdir:/home/bot/app/botapi/workdir
    ports:
      - 5005:5005
    env_file:
      - .env
    networks:
      smartnet:
        ipv4_address: 170.20.0.6
  audioconverter:
    container_name: audioconverter
    restart: always
    build:
      context: ../../../
      dockerfile: audio/Dockerfile
    volumes:
      - ../../../data/converter/logs:/home/bot/app/logs
      - ../../../data/converter/oom:/home/bot/app/oom
      - ../../../data/media/downloads:/tmp/media/downloads
      - ../../../data/media/uploads:/tmp/media/uploads
      - ../../../data/media/temp:/tmp/media/temp
      - ../../../../fonts:/usr/share/fonts/converter
      - ../../../data/botapi/workdir:/home/bot/app/botapi/workdir
    ports:
      - 5005:5005
    env_file:
      - .env
    networks:
      smartnet:
        ipv4_address: 170.20.0.7
  documentconverter:
    container_name: documentconverter
    restart: always
    build:
      context: ../../../
      dockerfile: document/Dockerfile
    volumes:
      - ../../../data/converter/logs:/home/bot/app/logs
      - ../../../data/converter/oom:/home/bot/app/oom
      - ../../../data/media/downloads:/tmp/media/downloads
      - ../../../data/media/uploads:/tmp/media/uploads
      - ../../../data/media/temp:/tmp/media/temp
      - ../../../../fonts:/usr/share/fonts/converter
      - ../../../data/botapi/workdir:/home/bot/app/botapi/workdir
    ports:
      - 5005:5005
    env_file:
      - .env
    depends_on:
      - url2api
  converter:
    container_name: converter
    restart: always
    build: ../../../
    ports:
      - 5005:5005
    volumes:
      - ../../../data/converter/logs:/home/bot/app/logs
      - ../../../data/converter/oom:/home/bot/app/oom
      - ../../../data/media/downloads:/tmp/media/downloads
      - ../../../data/media/uploads:/tmp/media/uploads
      - ../../../data/media/temp:/tmp/media/temp
      - ../../../../fonts:/usr/share/fonts/converter
      - ../../../data/botapi/workdir:/home/bot/app/botapi/workdir
    env_file:
      - .env
    networks:
      smartnet:
        ipv4_address: 170.20.0.5
    depends_on:
      - url2api
  url2api:
    container_name: url2api
    restart: always
    build: ../../../../url-to-pdf-api/
    networks:
      smartnet:
        ipv4_address: 170.20.0.6

networks:
  smartnet:
    external: true
