version: '2.4'
services:
  converter:
    container_name: converter
    restart: always
    build:
      context: ../../../
      dockerfile: videoaudio/Dockerfile
    volumes:
      - ../../../data/converter/logs:/home/bot/app/logs
      - ../../../data/converter/oom:/home/bot/app/oom
      - ../../../data/shr:/tmp/shr
      - ../../../../fonts:/usr/share/fonts/converter
      - ../../../data/botapi/workdir:/home/bot/app/botapi/workdir
    ports:
      - 5005:5005
    mem_limit: 4g
    memswap_limit: 8g
    env_file:
      - .env
    depends_on:
      - url2api
  url2api:
    container_name: url2api
    restart: always
    build: ../../../../url-to-pdf-api/

networks:
  default:
    external:
      name: fileutils
