version: '3.5'
services:
  db:
    container_name: db
    image: postgres:alpine
    restart: always
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - 5431:5432
    env_file:
      - .common.env
    networks:
      smartnet:
        ipv4_address: 170.20.0.2
  redis:
    container_name: redis
    image: redis:alpine
    restart: always
    ports:
      - 6378:6379
    command:
      - 'redis-server'
      - '--save 900 1'
      - '--save 300 10'
      - '--save 60 10000'
    volumes:
      - ../../../data/redis:/data
    networks:
      smartnet:
        ipv4_address: 170.20.0.3
  botapi:
    container_name: botapi
    restart: always
    build: ../../../bot-api/
    ports:
      - 8081:8081
      - 8082:8082
    volumes:
      - type: bind
        source: ../../../data/botapi/logs
        target: /home/bot/logs
      - type: bind
        source: ../../../data/botapi/workdir
        target: /home/bot/workdir/1119541928:AAFiil_pWtM2YevKfifi-p8XxR0delkEeuw
    env_file:
      - .common.env
    networks:
      smartnet:
        ipv4_address: 170.20.0.4

volumes:
  pgdata:
    external: true

networks:
  smartnet:
    external: true
